INSERT INTO products (name, price, description, image_path, created_at) VALUES
('Spanish Latte - TRUTH', 49, 'Hot Coffee - Truth', 'https://i.postimg.cc/MKyTN3Fv/Gemini-Generated-Image-gmxkl1gmxkl1gmxk.png', NOW()),
('Spanish Latte - UNITY', 69, 'Hot Coffee - Unity', 'https://i.postimg.cc/MKyTN3Fv/Gemini-Generated-Image-gmxkl1gmxkl1gmxk.png', NOW()),
('Macchiato - TRUTH', 49, 'Hot Coffee - Truth', 'https://i.postimg.cc/MKyTN3Fv/Gemini-Generated-Image-gmxkl1gmxkl1gmxk.png', NOW()),
('Macchiato - UNITY', 69, 'Hot Coffee - Unity', 'https://i.postimg.cc/MKyTN3Fv/Gemini-Generated-Image-gmxkl1gmxkl1gmxk.png', NOW()),
('Hazelnut Latte - TRUTH', 49, 'Hot Coffee - Truth', 'https://i.postimg.cc/MKyTN3Fv/Gemini-Generated-Image-gmxkl1gmxkl1gmxk.png', NOW()),
('Hazelnut Latte - UNITY', 69, 'Hot Coffee - Unity', 'https://i.postimg.cc/MKyTN3Fv/Gemini-Generated-Image-gmxkl1gmxkl1gmxk.png', NOW()),
('Americano - TRUTH', 49, 'Hot Coffee - Truth', 'https://i.postimg.cc/MKyTN3Fv/Gemini-Generated-Image-gmxkl1gmxkl1gmxk.png', NOW()),
('Americano - UNITY', 69, 'Hot Coffee - Unity', 'https://i.postimg.cc/MKyTN3Fv/Gemini-Generated-Image-gmxkl1gmxkl1gmxk.png', NOW()),
('Caramel Macchiato - TRUTH', 49, 'Hot Coffee - Truth', 'https://i.postimg.cc/MKyTN3Fv/Gemini-Generated-Image-gmxkl1gmxkl1gmxk.png', NOW()),
('Caramel Macchiato - UNITY', 69, 'Hot Coffee - Unity', 'https://i.postimg.cc/MKyTN3Fv/Gemini-Generated-Image-gmxkl1gmxkl1gmxk.png', NOW()),
('Vanilla Latte - TRUTH', 49, 'Hot Coffee - Truth', 'https://i.postimg.cc/MKyTN3Fv/Gemini-Generated-Image-gmxkl1gmxkl1gmxk.png', NOW()),
('Vanilla Latte - UNITY', 69, 'Hot Coffee - Unity', 'https://i.postimg.cc/MKyTN3Fv/Gemini-Generated-Image-gmxkl1gmxkl1gmxk.png', NOW()),
('Iced Spanish Latte - UNITY', 49, 'Iced Coffee - Unity', 'https://i.postimg.cc/sXFC3wtT/Gemini-Generated-Image-3g3a3x3g3a3x3g3a.png', NOW()),
('Iced Spanish Latte - LOVE', 59, 'Iced Coffee - Love', 'https://i.postimg.cc/sXFC3wtT/Gemini-Generated-Image-3g3a3x3g3a3x3g3a.png', NOW()),
('Iced Macchiato - UNITY', 49, 'Iced Coffee - Unity', 'https://i.postimg.cc/sXFC3wtT/Gemini-Generated-Image-3g3a3x3g3a3x3g3a.png', NOW()),
('Iced Macchiato - LOVE', 59, 'Iced Coffee - Love', 'https://i.postimg.cc/sXFC3wtT/Gemini-Generated-Image-3g3a3x3g3a3x3g3a.png', NOW()),
('Iced Hazelnut Latte - UNITY', 49, 'Iced Coffee - Unity', 'https://i.postimg.cc/sXFC3wtT/Gemini-Generated-Image-3g3a3x3g3a3x3g3a.png', NOW()),
('Iced Hazelnut Latte - LOVE', 59, 'Iced Coffee - Love', 'https://i.postimg.cc/sXFC3wtT/Gemini-Generated-Image-3g3a3x3g3a3x3g3a.png', NOW()),
('Iced Americano - UNITY', 49, 'Iced Coffee - Unity', 'https://i.postimg.cc/sXFC3wtT/Gemini-Generated-Image-3g3a3x3g3a3x3g3a.png', NOW()),
('Iced Americano - LOVE', 59, 'Iced Coffee - Love', 'https://i.postimg.cc/sXFC3wtT/Gemini-Generated-Image-3g3a3x3g3a3x3g3a.png', NOW()),
('Iced Caramel Macchiato - UNITY', 49, 'Iced Coffee - Unity', 'https://i.postimg.cc/sXFC3wtT/Gemini-Generated-Image-3g3a3x3g3a3x3g3a.png', NOW()),
('Iced Caramel Macchiato - LOVE', 59, 'Iced Coffee - Love', 'https://i.postimg.cc/sXFC3wtT/Gemini-Generated-Image-3g3a3x3g3a3x3g3a.png', NOW()),
('Iced Vanilla Latte - UNITY', 49, 'Iced Coffee - Unity', 'https://i.postimg.cc/sXFC3wtT/Gemini-Generated-Image-3g3a3x3g3a3x3g3a.png', NOW()),
('Iced Vanilla Latte - LOVE', 59, 'Iced Coffee - Love', 'https://i.postimg.cc/sXFC3wtT/Gemini-Generated-Image-3g3a3x3g3a3x3g3a.png', NOW()),
('Strawberry Milk - UNITY', 69, 'Milk Series - Strawberry Milk (Unity)', 'https://i.postimg.cc/7hqHkwcS/Gemini-Generated-Image-oix302oix302oix3.png', NOW()),
('Strawberry Milk - LOVE', 79, 'Milk Series - Strawberry Milk (Love)', 'https://i.postimg.cc/7hqHkwcS/Gemini-Generated-Image-oix302oix302oix3.png', NOW()),
('Strawberry Hazelnut - UNITY', 69, 'Milk Series - Strawberry Hazelnut (Unity)', 'https://i.postimg.cc/7hqHkwcS/Gemini-Generated-Image-oix302oix302oix3.png', NOW()),
('Strawberry Hazelnut - LOVE', 79, 'Milk Series - Strawberry Hazelnut (Love)', 'https://i.postimg.cc/7hqHkwcS/Gemini-Generated-Image-oix302oix302oix3.png', NOW()),
('Choco Milk - UNITY', 69, 'Milk Series - Choco Milk (Unity)', 'https://i.postimg.cc/7hqHkwcS/Gemini-Generated-Image-oix302oix302oix3.png', NOW()),
('Choco Milk - LOVE', 79, 'Milk Series - Choco Milk (Love)', 'https://i.postimg.cc/7hqHkwcS/Gemini-Generated-Image-oix302oix302oix3.png', NOW()),
('Strawberry Fruit Soda', 49, 'Fruit Soda - Strawberry', 'https://i.postimg.cc/7hqHkwcS/Gemini-Generated-Image-oix302oix302oix3.png', NOW()),
('Blueberry Fruit Soda', 49, 'Fruit Soda - Blueberry', 'https://i.postimg.cc/7hqHkwcS/Gemini-Generated-Image-oix302oix302oix3.png', NOW()),
('Green Apple Fruit Soda', 49, 'Fruit Soda - Green Apple', 'https://i.postimg.cc/7hqHkwcS/Gemini-Generated-Image-oix302oix302oix3.png', NOW()),
('Blue Lemonade Fruit Soda', 49, 'Fruit Soda - Blue Lemonade', 'https://i.postimg.cc/7hqHkwcS/Gemini-Generated-Image-oix302oix302oix3.png', NOW()),
('Lychee Fruit Soda', 49, 'Fruit Soda - Lychee', 'https://i.postimg.cc/7hqHkwcS/Gemini-Generated-Image-oix302oix302oix3.png', NOW()),
('Four Season Fruit Soda', 49, 'Fruit Soda - Four Season', 'https://i.postimg.cc/7hqHkwcS/Gemini-Generated-Image-oix302oix302oix3.png', NOW());
